### ISSUE TITLE
Error after updating to the newest version of angular2-meteor and angular2 beta.12

### ISSUE THREAD

**Issue by studiollama** [Urigo/angular2-meteor-accounts-ui#2]
I get this error after updating to the newest version of angular2-meteor and angualr2 beta.12: 

Uncaught TypeError: core_1.View is not a function(anonymous function) @ lang.ts:479(anonymous function) @ lang.ts:479__webpack_require__ @ lang.ts:479c @ lang.ts:479meteorInstall.node_modules.angular2-meteor-accounts-ui.login-buttons.js @ lang.ts:479fileEvaluate @ modules-runtime.js?hash=939c79d…:158require @ modules-runtime.js?hash=939c79d…:92(anonymous function) @ lang.ts:479__webpack_require__ @ lang.ts:479(anonymous function) @ lang.ts:479__webpack_require__ @ lang.ts:479(anonymous function) @ lang.ts:479meteorInstall.node_modules.angular2-meteor-accounts-ui.index.js @ lang.ts:479fileEvaluate @ modules-runtime.js?hash=939c79d…:158require @ modules-runtime.js?hash=939c79d…:92meteorInstall.client.parties-list.parties-list.component.ts @ parties-list.component.ts:8fileEvaluate @ modules-runtime.js?hash=939c79d…:158require @ modules-runtime.js?hash=939c79d…:92(anonymous function) @ parties.ts:16

I'm also getting this when starting the meteor server:

"!!./../node_modules/css-loader/index.js!./../node_modules/less-loader/index.js!./login-buttons.less"
in
/E/Users/Matt/Documents/Meteor/socially/socially/node_modules/angular2-meteor-accounts-ui/login-buttons.js
(web.browser)

I noticed you did some updates that say updating to the newest version.  But I have deleted the node package and re installed it, so I believe I have the most recent version.

**Comment by twastvedt** [comment]
I have the same issue. The `core_1.View` part is fixed with the latest commit (e52d84). The second part is not. I've found that commenting out lines 228-232 in `node_modules/angular2-meteor-accounts-ui/login-buttons.js` eliminates the error, but I'm guessing from the code that that also disables an update when you change css files?

**Comment by Urigo** [comment]
Have you tried the latest version of the tutorial?
it has been updated to Meteor 1.3 and we also fixed a few issues with this npm package

**Comment by twastvedt** [comment]
On my own app I'm still seeing:

```
Unable to resolve some modules:

  "!!./../node_modules/css-loader/index.js!./../node_modules/less-loader/index.js!./login-buttons.less" in
/C/Users/twastvedt/Documents/Zahner/Alfred-Zahner/az-app/node_modules/angular2-meteor-accounts-ui/login-buttons.js
(web.browser)
```

right before the app starts. The app still starts successfully though.

**Comment by studiollama** [comment]
I also still see that unable to resolve modules.  However the core_1.View issue is gone, though I needed to go into login-buttons.d.ts and remove import { Tracker } from 'meteor/tracker'; as I get typescript errors in my ide due to meteor being the old Atmosphere package I assume.

**Comment by twastvedt** [comment]
I just put up a test repo for an issue in barbatus:typescript and added a branch that, for me, throws the error with this package: [https://github.com/twastvedt/barbatus-typescript-bug-demo/tree/angular2-meteor-accounts-ui-bug](https://github.com/twastvedt/barbatus-typescript-bug-demo/tree/angular2-meteor-accounts-ui-bug).

**Comment by dotansimha** [comment]
Already fixed so it sound weird... actually caused by the fact that Angular 2 removed `@View` and all it's properties moved to `@Component`, you can see that we already fixed it:
https://github.com/Urigo/angular2-meteor-accounts-ui/blob/master/modules/login-buttons.ts#L13-L18

And also, in the compiled file:
https://github.com/Urigo/angular2-meteor-accounts-ui/blob/master/build/login-buttons.js#L170-L175

Please make sure that you have the latest version and that you import the files from the root folder only and not the "TS" files from the `modules` directory.

**Comment by twastvedt** [comment]
@dotansimha Yes that part is fixed, as both @studiollama and I mentioned above. The other error we were seeing, though, is still there:

```
Unable to resolve some modules:

  "!!./../node_modules/css-loader/index.js!./../node_modules/less-loader/index.js!./login-buttons.less" in
/C/Users/twastvedt/Documents/Zahner/Alfred-Zahner/az-app/node_modules/angular2-meteor-accounts-ui/login-buttons.js
(web.browser)
```

**Comment by wintersa** [comment]
I have the same issue as @twastvedt and @studiollama . I try to complete the Socially tutorial, but am stuck in chapter 8. I updated meteor to version 1.3.2.4 for my packages. I was having real fun with meteor as a newbie, but then I ran into trouble with the tsconfig.json, and packages. Wish it was just as easy, as was presented on Vegas. Though am sure I will get there. 

For the tutorial I needed to download and use a custom meteor typings file. 
It was recommended in the Tutorial to downloaded the typing file from this location:             
- https://gist.github.com/tomitrescak/8366ce98f1857e202ea8

**Meteor error**
`
Unable to resolve some modules:

  "!!./../node_modules/css-loader/index.js!./../node_modules/less-loader/index.js!./login-buttons.less" in /Users/Tony/Library/Mobile
Documents/com~apple~CloudDocs/Software/Development/Atom/seeds/socially/node_modules/angular2-meteor-accounts-ui/login-buttons.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save !!.

`

**tsconfig.json**
`
{
  "atom": {
    "rewriteTsconfig": false
  },
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "commonjs",
    "target": "es5",
    "isolatedModules": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "removeComments": false,
    "noImplicitAny": false,
    "sourceMap": true
  },
  "files": [
    "typings/main.d.ts",
    "typings/meteor.d.ts",
    "typings/party.d.ts"
  ]
}

**Folder structure**

socially/
├── client
├── collections
├── node_modules
├── old
├── package.json
├── server
├── tsconfig.json
└── typings

**Installed packages**
- meteor add angular2-compilers
- meteor npm install --save angular2-meteor
- meteor npm install --save meteor-node-stubs
- meteor remove insecure
- meteor npm install --save angular2-meteor-accounts-ui
- meteor npm install --save angular2-meteor-auto-bootstrap
- meteor remove blaze-html-templates
- npm install typings -g
- typings install es6-promise
- typings install es6-shim --ambient

**meteor list**
- angular2-compilers     0.5.6  Angular 2 Templates, HTML and TypeScript compilers for Meteor
- autopublish            1.0.7  (For prototyping only) Publish the entire database to all clients
- es5-shim               4.5.10  Shims and polyfills to improve ECMAScript 5 support
- jquery                 1.11.8  Manipulate the DOM using CSS selectors
- meteor-base            1.0.4  Packages that every Meteor app needs
- mobile-experience      1.0.4  Packages for a great mobile user experience
- mongo                  1.1.7  Adaptor for using MongoDB and Minimongo over DDP
- reactive-var           1.0.9  Reactive variable
- standard-minifier-css  1.0.6  Standard css minifier used with Meteor apps by default.
- standard-minifier-js   1.0.6  Standard javascript minifiers used with Meteor apps by default.
- tracker                1.0.13  Dependency tracker to allow reactive callbacks

`

**Comment by kfirufk** [comment]
same problem. any updates?

**Comment by wintersa** [comment]
I struggle for a few days with this issue now.  I reviewed the code on the Github repository of @Urigo with my own code, and I could not find an issue in mine.

<b>Clone of my code on GitHub<b>
<a href="https://github.com/wintersa/angular2-meteor-socially">Github Code Repository</a>

Here I found a similar issue. 
<b>Issue</b>
<a href="https://github.com/Urigo/angular2-meteor/issues/236">angular2-pagination</a>

**Comment by wintersa** [comment]
After digging into the code of
`node_modules/angular2-meteor-accounts-ui/login-buttons.js`  

I think that the code block, lines 225 - 236 is responsible for the error i got.  When I looked again at the error, I saw that I possibly needed the NPM package **css-loader**. The package was not present in my node_modules directory, I installed the package and got unexpected result.

`meteor npm install --save css-loader`

I can see now the login form with buttons and is fully functional.  The error is still present, but I'm happy I can get to the next step of the tutorial. A better description of my issue can be found on GitHub. 

<a href="https://github.com/wintersa/angular2-meteor-socially">Github Code</a>

**Comment by MilosStanic** [comment]
I can also report error: 

```
Unable to resolve some modules:


"!!./../node_modules/css-loader/index.js!./../node_modules/less-loader/index.js!./login-buttons.less"
in
/home/milos/devel/recnik/node_modules/angular2-meteor-accounts-ui/login-buttons.js
(web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save !!.
```

But the module works.

**Comment by stefanholzapfel** [comment]
Same here, installing css-loader manually makes no difference.

**Comment by youngboy** [comment]
if you look in ./login-buttons.js, you will find that code with path `!!./../node_modules/css-loader...` is actually wrapped inside a false if body.

This output from webpack's style-loader, and it is checking  [HMR](http://webpack.github.io/docs/hot-module-replacement-with-webpack.html) , somehow meteor/typescript compiler is parsing the path shouldn't be reach.

And I think it is totally ok to ignore this error right now, and my workaround is comment out line 225~236 in ./login-button.js

```
if (false) {
  //..
}
```

**Comment by dotansimha** [comment]
Just tested the package now. 
The package works great with a new, clean project with all the up-to-date packages. 
The import warning you get caused by Meteor that tried to understand the WebPack imports - but he actually can't. 
The package works - but needs some cleanup. 

I'm closing this issue since it's not an error, and the "View" error was resolved long ago. 
Please open a new issue if you still having a troubles - I opened an issue to cleanup and remove the WebPack errors. (https://github.com/Urigo/angular2-meteor-accounts-ui/issues/12)
